config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :dashboards, except: :destoy
  resources :user_dashboards
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  has_many :user_dashboards, dependent: :destroy
  validates :title, :description, presence: true
end

# == Schema Information
#
# Table name: dashboards
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_dashboards, dependent: :destroy
  has_many :dashboards, through: :dashboards
end

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  first_name             :string
#  last_name              :string
#  phone                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#

app/models/user_dashboard.rb
class UserDashboard < ActiveRecord::Base
  include RailsSortable::Model

  belongs_to :user
  belongs_to :dashboard

  validates :user_id, :dashboard_id, presence: true
  validates :user_id, uniqueness: { scope: :dashboard_id }

  delegate :title, :description, to: :dashboard, allow_nil: true

  set_sortable :order_number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  PER = 4

  def index
    @dashboards = Dashboard.all.page(params[:page]).per(PER)
  end

  def new
    @dashboard = Dashboard.new
  end

  def create
    @dashboard = Dashboard.new(dashboard_params)
    if @dashboard.save
      flash[:success] = 'successfully created'
      redirect_to dashboards_path
    else
      flash[:errod] = 'Something get wrong'
      redirect_back(fallback_location: new_dashboard_path)
    end
  end

  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  def update
    @dashboard = Dashboard.find(params[:id])
    if @dashboard.update(dashboard_params)
      flash[:success] = 'Successfully saved'
      redirect_to dashboards_path
    else
      flash[:errod] = 'Something get wrong'
      redirect_back(fallback_location: edit_dashboard_path(@dashboard))
    end
  end

  private

  def dashboard_params
    params.require(:dashboard).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @user_dashboards = current_user.user_dashboards.order(order_number: :asc)
      render 'user_dashboards/index'
    end
  end
end

app/controllers/user_dashboards_controller.rb
class UserDashboardsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user_dashboard = current_user.user_dashboards.new(user_dashboard_params)
    @user_dashboard.save ? render_success : render_error
  end

  def destroy
    @user_dashboard = UserDashboard.find(params[:id])
    @user_dashboard.destroy ? render_success : render_error
  end

  private

  def render_success
    flash[:success] = 'successfully'
    redirect_to root_path
  end

  def render_error
    flash[:errod] = 'Something get wrong'
    redirect_back(fallback_location: dashboards_path)
  end

  def user_dashboard_params
    params.permit(:dashboard_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_recourse, only: [:edit, :update]

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Successfully updated'
      redirect_to root_path
    else
      flash[:error] = 'Errors occured'
      redirect_back(fallback_location: edit_user_path(@user))
    end
  end

  private

  def find_recourse
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :phone
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success' then 'alert-success'
    when 'error' then 'alert-danger'
    when 'alert' then 'alert-warning'
    when 'notice' then 'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/application/_flash.html.haml
- flash.each do |type, msg|
  %div{ class: "alert #{bootstrap_class_for_flash(type)} alert-dismissable" }
    = msg

app/views/application/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_path } Home
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li
            = link_to 'Manage Dashboards', dashboards_path
          %li
            = link_to 'Profile', edit_user_path(current_user)
          %li
            = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn'
        - else
          %li
            = link_to 'Sign in', new_user_session_path, class: 'btn'

app/views/dashboards/_form.html.haml
= bootstrap_form_for(@dashboard) do |f|
  = f.text_field :title
  = f.text_area :description
  = f.submit 'Save', class: 'btn btn-success'

app/views/dashboards/edit.html.haml
.row
  .page-header
    %h2 Edit Dashboard
  = render 'form'

app/views/dashboards/index.html.haml
.row
  = render partial: 'application/flash', flash: flash
.row
  = link_to 'Create dashboard', new_dashboard_path, class: 'btn btn-success'
  .page-header
    %h2 Dashboards list
  - @dashboards.each do |dashboard|
    .panel.panel-default
      .panel-heading
        .panel-title= dashboard.title
      .panel-body
        = dashboard.description
      .panel-footer
        = link_to 'Edit', edit_dashboard_path(dashboard), class: 'btn btn-warning'
        - user_dashboard = current_user.user_dashboards.find_by(dashboard_id: dashboard.id)
        - if user_dashboard
          = link_to 'Remove from my menu', user_dashboard_path(user_dashboard), method: :delete, class: 'btn btn-danger'
        - else
          = link_to 'Add to my menu', user_dashboards_path(dashboard_id: dashboard.id), method: :post, class: 'btn btn-info'

  = paginate @dashboards, theme: 'twitter-bootstrap-3'

app/views/dashboards/new.html.haml
= bootstrap_form_for(@dashboard) do |f|
  = f.text_field :title
  = f.text_area :description
  = f.submit 'Create', class: 'btn btn-success'

app/views/home/index.html.haml
.row
  = render partial: 'application/flash', flash: flash
  .page-header
    %h1.text-center Hi there
.row
  .panel.panel-default
    .panel-heading.text-center To access to personal Dashboards you have to authorize
    .panel-body
      = link_to 'Sign in', new_user_session_path, class: 'btn btn-info col-md-4'
      = link_to 'Sign up', new_user_registration_path, class: 'btn btn-info col-md-4 col-md-offset-4'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %titleRelaxGamesTask
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'application/header'
    .container-fluid
      .col-md-6.col-md-offset-3
        = yield

app/views/user_dashboards/index.html.haml
.row
  = render partial: 'application/flash', flash: flash
  .page-header
    %h2 My Dashboards
  - if @user_dashboards.any?
    .alert.alert-info
      Drag and drop dashboards to change order
    #wrapper
      - @user_dashboards.each do |user_dashboard|
        .panel.panel-default{ id: user_dashboard.sortable_id }
          .panel-heading
            .panel-title= user_dashboard.title
          .panel-body
            = user_dashboard.description
          .panel-footer
            / = link_to 'Edit', edit_user_dashboard_path(user_dashboard.id), class: 'btn btn-info'
            = link_to 'Remove', user_dashboard_path(user_dashboard.id), method: :delete, class: 'btn btn-danger'

  - else
    .alert.alert-info
      Go to the
       
      = link_to 'Manage Dashboard', dashboards_path

      page to add Dashboards to you personal menu page
    
:javascript
  $(document).ready( function() {
    $('#wrapper').railsSortable();
  } );

app/views/users/edit.html.haml
.row
  .page-header
    %h2 Edit my profile
  = bootstrap_form_for(@user) do |f|
    = f.text_field :email, disabled: true
    = f.text_field :first_name
    = f.text_field :last_name
    = f.phone_field :phone
    = f.submit 'Save', class: 'btn btn-success'

%h4
  = link_to 'Change login info', edit_user_registration_path